const ADD_PROFILE_POST = "ADD_PROFILE_POST";
const ADD_PROFILE_POST_TEXT = "ADD_PROFILE_POST_TEXT";
const SHOW_PROFILE = "SHOW_PROFILE";

export enum PROFILE_TYPES {
    ADD_PROFILE_POST,
    ADD_PROFILE_POST_TEXT,
    SHOW_PROFILE,
}