const SHOW_NEXT_USERS = "SHOW_NEXT_USERS";
const SHOW_MORE_USERS = "SHOW_MORE_USERS";
const FOLLOW_USER = "FOLLOW_USER";
const UN_FOLLOW_USER = "UN_FOLLOW_USER";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_TOTAL_COUNT = "SET_TOTAL_COUNT";
const TOGGLE_IS_FETCHING = "TOGGLE_IS_FETCHING";

export enum USERS_TYPES {
    SHOW_NEXT_USERS,
    SHOW_MORE_USERS,
    FOLLOW_USER,
    UN_FOLLOW_USER,
    SET_CURRENT_PAGE,
    SET_TOTAL_COUNT,
    TOGGLE_IS_FETCHING,
}